/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface RuiApp {
    }
    interface RuiBox {
        "direction": string;
        "fill": boolean;
        "fixed": boolean;
        "gap": number;
        "gutter": number;
        "height": number;
        "horizontal": string;
        "name": string;
        "vertical": string;
        "width": number;
    }
    interface RuiLayout {
        "direction": string;
        "gap": number;
        "gutter": number;
        "horizontal": string;
        "name": string;
        "vertical": string;
    }
}
declare global {
    interface HTMLRuiAppElement extends Components.RuiApp, HTMLStencilElement {
    }
    var HTMLRuiAppElement: {
        prototype: HTMLRuiAppElement;
        new (): HTMLRuiAppElement;
    };
    interface HTMLRuiBoxElement extends Components.RuiBox, HTMLStencilElement {
    }
    var HTMLRuiBoxElement: {
        prototype: HTMLRuiBoxElement;
        new (): HTMLRuiBoxElement;
    };
    interface HTMLRuiLayoutElement extends Components.RuiLayout, HTMLStencilElement {
    }
    var HTMLRuiLayoutElement: {
        prototype: HTMLRuiLayoutElement;
        new (): HTMLRuiLayoutElement;
    };
    interface HTMLElementTagNameMap {
        "rui-app": HTMLRuiAppElement;
        "rui-box": HTMLRuiBoxElement;
        "rui-layout": HTMLRuiLayoutElement;
    }
}
declare namespace LocalJSX {
    interface RuiApp {
    }
    interface RuiBox {
        "direction"?: string;
        "fill"?: boolean;
        "fixed"?: boolean;
        "gap"?: number;
        "gutter"?: number;
        "height"?: number;
        "horizontal"?: string;
        "name"?: string;
        "vertical"?: string;
        "width"?: number;
    }
    interface RuiLayout {
        "direction"?: string;
        "gap"?: number;
        "gutter"?: number;
        "horizontal"?: string;
        "name"?: string;
        "vertical"?: string;
    }
    interface IntrinsicElements {
        "rui-app": RuiApp;
        "rui-box": RuiBox;
        "rui-layout": RuiLayout;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "rui-app": LocalJSX.RuiApp & JSXBase.HTMLAttributes<HTMLRuiAppElement>;
            "rui-box": LocalJSX.RuiBox & JSXBase.HTMLAttributes<HTMLRuiBoxElement>;
            "rui-layout": LocalJSX.RuiLayout & JSXBase.HTMLAttributes<HTMLRuiLayoutElement>;
        }
    }
}
